---
title: "In-class Ex03"
author: "Zhang Chenbin"
date: "`r s.Date()"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  message: false
  freeze: true
format: 
  html:
    code-fold: true
---

```{r}
 pacman::p_load(sf, spNetwork, tmap, tidyverse)
```

```{r}
network <- st_read(dsn="data/geospatial", 
                   layer="Punggol_St")
```

```{r}
childcare <- st_read(dsn="data/geospatial",
                     layer="Punggol_CC") %>%
  st_zm(drop = TRUE,
        what = "ZM")
```

```{r}
plot(st_geometry(network))
plot(childcare,add=T,col='red',pch = 19)
```

```{r}
plot(network)
plot(childcare,add=T,col='red',pch = 19)
```

```{r}
tmap_mode('view')
tm_shape(childcare) + 
tm_dots(col = "darkgreen") +
tm_shape(network) +
tm_lines()
tmap_mode('plot')

```

```{r}
lixels <- lixelize_lines(network,
                       700,
                       mindist = 350)
```

```{r}
samples <- lines_center(lixels)

tmap_mode('view')
tm_shape(lixels) +
  tm_lines() +
tm_shape(samples) +
  tm_dots(size = 0.01)
tmap_mode('plot')

```

```{r}
#| eval: false
densities <- nkde(network, 
                  events = childcare,
                  w = rep(1, nrow(childcare)),
                  samples = samples,
                  kernel_name = "quartic",
                  bw = 300, 
                  div= "bw", 
                  method = "simple")
```

```{r}
kfun_childcare <- kfunctions(network, 
                             childcare,
                             start = 0, 
                             end = 1000, 
                             step = 50, 
                             width = 50, 
                             nsim = 50, 
                             resolution = 50,
                             verbose = FALSE, 
                             conf_int = 0.05)
```

```{r}
kfun_childcare$plotg
```
