---
title: "In-class_EX04"
author: "Zhang Chenbin"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
  cache: TRUE
format: 
  html:
    code-fold: true
---

```{r}
pacman::p_load(sf, spdep, tmap, tidyverse, knitr, GWmodel, ggstatsplot)
```

```{r}
hunan_sf <- st_read(dsn = "data/geospatial",
                 layer = "Hunan")
```

```{r}
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
hunan_join <- left_join(hunan_sf, hunan2012)%>%
  select(1:3, 7, 9, 15, 16, 31, 32)
```

```{r}
hunan_sp <- hunan_join %>%
  as_Spatial()
```

```{r}
hunan_sp <- hunan_join %>%
  as_Spatial()
```

```{r}
bw_CV <- bw.gwr(GDPPC ~ 1,
                data = hunan_sp,
                approach = "CV",
                adaptive = TRUE,
                kernel = "bisquare",
                longlat = T)
```

```{r}
bw_AIC <- bw.gwr(GDPPC ~ 1,
                data = hunan_sp,
                approach = "CV",
                adaptive = TRUE,
                kernel = "bisquare",
                longlat = T)
```

```{r}
gwstat <- gwss(vars = "GDPPC",
               data = hunan_sp,
               bw = bw_AIC,
               adaptive = TRUE,
               kernel = "bisquare",
                longlat = T)
```

```{r}
gwstat_df <- as.data.frame(gwstat$SDF)
```

```{r}
hunan_gstat <- cbind(hunan_sf, gwstat_df)
```

```{r}
tm_shape(hunan_gstat) +
  tm_fill("GDPPC_LM",
          n = 5,
          style = "quantile") +
  tm_borders(alpha = 0.5) +
  tm_layout(main.title = "Distribution of geography weighted mean",
            main.title.position = "center",
            main.title.size = 1,
            legend.text.size = 0.5,
            legend.height = 1.5,
            legend.width = 1.5,
            frame = TRUE)
```

```{r}
gwstats <- gwss(vars = c("GDPPC", "GIO"),
               data = hunan_sp,
               bw = bw_AIC,
               adaptive = TRUE,
               kernel = "bisquare",
                longlat = T)
```

```{r}
# gwstat_df <- as.data.frame(gwstats$SDF) %>%
#  select(c(12,13)) %>%
#  rename(gwCorr = Corr)
```
