---
title: "test"
---

```{r}
pacman::p_load(sf, tidyverse, tmap, spNetwork)
```

```{r}
#! eval:false
acc <- read_csv("data/thai_road_accident_2019_2022.csv") %>%
  mutate(Month_num = month(incident_datetime)) %>%
  mutate(Month_fac = month(incident_datetime,
                       label = TRUE,
                       abbr = TRUE)) %>%
  mutate(dayofweek = weekdays(incident_datetime))%>%
  filter(!is.na(longitude) & !is.na(latitude)) %>%  # Remove rows with missing coordinates
  st_as_sf(coords = c("longitude", "latitude"),
                       crs=4326) %>%
  st_transform(crs = 32647)
```

```{r}
write_rds(acc, "data/acc.rds")
```

```{r}
acc <- read_rds("data/acc.rds")
```

```{r}
bangkok_acc_data <- acc %>%
  filter(province_en == "Bangkok")
head(bangkok_acc_data)
```

```{r}
write_rds(bangkok_acc_data,"data/bangkok_acc_data.rds")
```

```{r}
bangkok_acc_data <- read_rds("data/bangkok_acc_data.rds")
```

```{r}
thai_one_map <- st_read(dsn = "data",
                        layer = "hotosm_tha_roads_lines_shp")
```

```{r}
thai_one_map
```

```{r}
admin_boundaries <- st_read(dsn = "data",
                        layer = "tha_admbnda_adm1_rtsd_20220121")
```

```{r}
bangkok_boundary <- admin_boundaries %>%
  filter(ADM1_EN == "Bangkok")
```

```{r}
st_crs(thai_one_map)  # 检查道路数据的 CRS
st_crs(bangkok_boundary)  # 检查曼谷边界数据的 CRS
```

```{r}
# 将 CRS 转换为 WGS 84 (EPSG:4326)
st_crs(thai_one_map) <- 4326

```

```{r}
bangkok_roads <- st_intersection(thai_one_map, bangkok_boundary)
head(bangkok_roads)
```

```{r}
# 绘制曼谷道路和事故数据
ggplot() +
  geom_sf(data = bangkok_roads, color = "blue", size = 0.5) +  # 曼谷的道路数据
  geom_sf(data = bangkok_acc_data, color = "red", size = 2, alpha = 0.6) +  # 曼谷的事故点数据
  labs(title = "Bangkok Roads and Accident Locations") +
  theme_minimal()

```